name = "alchemy-logs"
main = "src/index.js"
compatibility_date = "2026-09-01"

[[kv_namespaces]]
binding = "LOGS"
id = "0b184d430f96417ea537d089d3db0705"

# Set with: npx wrangler secret put ADMIN_KEY
