// Bakes world 1's locked icons from the design source into icons/world1.js, the file the game
// loads, so the game never depends on the design folder. Run it again only if a drawing changes.
// Usage: node tools/export-icons.mjs
import { writeFileSync, mkdirSync } from "node:fs";
import { w1icons, W1_DEFS } from "../design/_context/icon-art-w1.js";
import { HR_DEFS } from "../design/_context/icon-art-habitat-r.js";

mkdirSync(new URL("../icons/", import.meta.url), { recursive: true });
const body = [
  "// Generated by tools/export-icons.mjs from design/_context/icon-art-w1.js. Do not edit by hand.",
  "// The shared blur filters every icon points at; put in the page once.",
  `export const defs = ${JSON.stringify(W1_DEFS + HR_DEFS)};`,
  "export const icons = {",
  ...Object.entries(w1icons).map(([id, svg]) => `  ${id}: ${JSON.stringify(svg)},`),
  "};",
  "",
].join("\n");
writeFileSync(new URL("../icons/world1.js", import.meta.url), body);
console.log(`icons/world1.js: ${Object.keys(w1icons).length} icons, ${(body.length / 1024).toFixed(0)} KB`);
